export const ENABLE_SOLVE_BUTTON = 'ENABLE_SOLVE_BUTTON';
export const DISABLE_SOLVE_BUTTON = 'DISABLE_SOLVE_BUTTON';
export const SOLVE_START = 'SOLVE_START';
export const SOLVE_SUCCESS = 'SOLVE_SUCCESS';
export const SOLVE_SUCCESS_WITH_WARNING = 'SOLVE_SUCCESS_WITH_WARNING';
export const SOLVE_FAILURE = 'SOLVE_FAILURE';

export const CLEAR_SYNTAX_ERROR_MESSAGE = 'CLEAR_SYNTAX_ERROR_MESSAGE';
export const SET_SOLUTION = 'SET_SOLUTION';